### ISSUE TITLE
Add mute toggle and mute status to feedback

### ISSUE THREAD

**Issue by thingyt** [bitfocus/companion-module-sonos-speakers#4]
I'd love to have the mute status of speaker available as a feedback option. Since you can get volume back and the API references it in the same way, I'm assuming adding the mute should be quite easy. Unfortunately zero volume isn't the same as muting for feedback. 

As for why, we have a simple panel for people to mute, add or decrease volume we made using generic http post commands for a large shared lobby space with multiple speakers and areas. It would be great to have the easy option to mute areas and see when it is muted in feedback.

**Comment by Julusian** [comment]
This will be in the beta builds shortly
