### ISSUE TITLE
loadStreamUrl

### ISSUE THREAD

**Issue by kjetilpp** [bitfocus/companion-module-sonos-speakers#8]
Hello!
I would love to have the loadStreamUrl function. [docs](https://developer.sonos.com/reference/control-api/playbacksession/loadstreamurl/)

So i can play local (or remote radio) streams to sonos.

**Comment by Julusian** [comment]
This will be in the beta builds shortly

It's not the friendliest thing to use, as discovering the uris isnt always simple, but I have tested it with a couple of services (spotify track, tunein and bbc sounds)
